[runner]
fastReruns = false

[theme]
base = "light"
primaryColor = "#5068DB"
backgroundColor = "#F6F7FB"
secondaryBackgroundColor = "#EDF0F7"
textColor = "#16233B"
font = "sans serif"

[browser]
gatherUsageStats = false
